apiVersion: batch/v1
kind: CronJob
metadata:
  name: opensky-kafka-publisher-cronjob
  namespace: apache-plane-tracker
spec:
  schedule: "*/2 * * * *"  # Runs every 2mn
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: opensky-kafka-publisher
            image: abonnin33/opensky-kafka-publisher:latest
            env:
            - name: IS_DRY_RUN
              value: "${IS_DRY_RUN}"
            - name: KAFKA_BROKER
              value: "${KAFKA_BROKER}"
            - name: KAFKA_TOPIC
              value: "${KAFKA_TOPIC}"
            - name: LATITUDE_MIN
              value: "${LATITUDE_MIN}"
            - name: LATITUDE_MAX
              value: "${LATITUDE_MAX}"
            - name: LONGITUDE_MIN
              value: "${LONGITUDE_MIN}"
            - name: LONGITUDE_MAX
              value: "${LONGITUDE_MAX}"
          restartPolicy: OnFailure
